image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

pylint:
    stage: Static Analysis
    script:
        - pip install pylint --quiet
        - pylint --ignored-classes=_socketobject *.py

unit_test:
    stage: Test
    script:
    - pip install pytest --quiet
    - pytest
