test_script:
        tags:
            - telemetry
            - ci
        script:
            - pip install -r requirements.txt
            - python Test\CanReader_test.py test
            - echo Done