image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

pylint:
    stage: Static Analysis
    script:
        #- pip install pylint --quiet
        #- pylint --ignored-classes=_socketobject *.py
        - echo mozna priste, tedka pises jak curak

unit_test:
    stage: Test
    script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pip install pytest --quiet
    - pytest
